Feature: Pen test the Application
  Scenario: The zap report should not contain blocking vulnerabilities
    Given we have valid zap json alert output
    And the following false positive are ignored
      |url                    |parameter          |cweId      |wascId   |
      |http://petclinic-frontend-defaultns/|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/find|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/oups||200|13|
      |http://petclinic-frontend-defaultns/owners/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/vets.html|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners?lastName=ZAP|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/1|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/2|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/4|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/5|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/3|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/6|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/7|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/8|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/9|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/10|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/1/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/1/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/1/pets/1/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/2/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/1/pets/1/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/2/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/2/pets/2/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/2/pets/2/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/4/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/4/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/4/pets/5/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/4/pets/5/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/3/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/3/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/3/pets/4/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/3/pets/4/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/5/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/5/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/5/pets/6/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/5/pets/6/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/6/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/6/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/6/pets/8/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/6/pets/8/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/6/pets/7/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/6/pets/7/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/7/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/7/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/7/pets/9/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/7/pets/9/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/8/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/8/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/8/pets/10/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/9/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/8/pets/10/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/9/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/9/pets/11/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/9/pets/11/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/10/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/10/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/10/pets/12/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/10/pets/12/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/10/pets/13/visits/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/10/pets/13/edit|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/1/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/2/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/4/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/3/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/5/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/6/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/7/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/8/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/9/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/10/pets/new|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/edit?query=query+AND+1%3D1+--+|query|89|19|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/edit?query=query+AND+1%3D1+--+|X-Frame-Options|16|15|
      |http://petclinic-frontend-defaultns/owners/1/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/1/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/1/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/1/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/1/pets/1/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/1/pets/1/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/10/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/10/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/10/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/10/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/10/pets/12/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/10/pets/12/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/10/pets/13/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/10/pets/13/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/2/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/2/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/2/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/2/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/2/pets/2/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/2/pets/2/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/3/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/3/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/3/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/3/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/3/pets/4/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/3/pets/4/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/4/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/4/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/4/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/4/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/4/pets/5/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/4/pets/5/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/5/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/5/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/5/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/5/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/5/pets/6/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/5/pets/6/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/6/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/6/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/6/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/6/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/6/pets/7/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/6/pets/7/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/6/pets/8/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/6/pets/8/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/7/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/7/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/7/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/7/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/7/pets/9/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/7/pets/9/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/8/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/8/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/8/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/8/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/8/pets/10/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/8/pets/10/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/9/edit|firstName|120|7|
      |http://petclinic-frontend-defaultns/owners/9/edit|lastName|120|7|
      |http://petclinic-frontend-defaultns/owners/9/edit|address|120|7|
      |http://petclinic-frontend-defaultns/owners/9/edit|city|120|7|
      |http://petclinic-frontend-defaultns/owners/9/pets/11/edit|name|120|7|
      |http://petclinic-frontend-defaultns/owners/9/pets/11/visits/new|description|120|7|
      |http://petclinic-frontend-defaultns/owners/1/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/1/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/1/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/1/pets/1/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/10/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/10/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/10/pets/12/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/10/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/10/pets/13/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/2/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/2/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/2/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/2/pets/2/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/3/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/3/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/3/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/3/pets/4/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/4/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/4/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/4/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/4/pets/5/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/5/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/5/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/5/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/5/pets/6/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/6/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/6/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/6/pets/7/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/6/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/6/pets/8/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/7/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/7/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/7/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/7/pets/9/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/8/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/8/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/8/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/8/pets/10/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/9/edit|firstName|134|6|
      |http://petclinic-frontend-defaultns/owners/9/edit|lastName|134|6|
      |http://petclinic-frontend-defaultns/owners/9/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/9/pets/11/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/2/edit?query=query+AND+1%3D1+--+|query|89|19|
      |http://petclinic-frontend-defaultns/owners/2/pets/2/edit?query=query+AND+1%3D1+--+|query|89|19|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/edit?query=query%27+AND+%271%27%3D%271%27+--+|query|89|19|
      |http://petclinic-frontend-defaultns/owners/5/edit?query=query+AND+1%3D1+--+|query|89|19|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/edit?query=query+AND+1%3D1+--+|name|120|7|
      |http://petclinic-frontend-defaultns/owners/1/edit|city|134|6|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/edit|name|134|6|
      |http://petclinic-frontend-defaultns/owners/3/pets/3/edit?query=query+AND+1%3D1+--+|name|134|6|
      |http://petclinic-frontend-defaultns/owners/6/pets/7/edit|name|134|6|


    Then none of these risk levels should be present
      | risk |
      | Medium |
      | High |

